// Lista curta de senhas/chaves comuns, usada pelo brute-force HMAC.
// Em produção, isso viria de um arquivo maior (rockyou.txt, seclists) — aqui
// mantemos ~50 pra rodar rápido no cobaia.
//
// Ordem MAIS provável → menos provável. Chaves de dev quase sempre estão no topo.

const WORDLIST = [
	'123456',
	'password',
	'secret',
	'admin',
	'root',
	'segredo',
	'segredo123',
	'mysecret',
	'jwtsecret',
	'jwt_secret',
	'chave',
	'senha',
	'12345',
	'123456789',
	'qwerty',
	'abc123',
	'letmein',
	'test',
	'testing',
	'dev',
	'production',
	'staging',
	'apikey',
	'api_key',
	'token',
	'authtoken',
	'privatekey',
	'private_key',
	'key',
	'default',
	'changeme',
	'change_me',
	'welcome',
	'welcome123',
	'senha123',
	'admin123',
	'root123',
	'passw0rd',
	'p@ssw0rd',
	'iloveyou',
	'monkey',
	'dragon',
	'master',
	'sunshine',
	'shadow',
	'football',
	'baseball',
	'superman',
	'batman',
	'trustno1',
];

export { WORDLIST };
